FROM alpine:3.11

RUN apk update && apk add ca-certificates && apk add python3

RUN pip3 install --upgrade pip
RUN pip3 install -U cacli --index-url https://carepo.system.cyberarmorsoft.com/repository/cyberarmor-pypi-dev.group/simple
